### ISSUE TITLE
Support for Multi-Module Builds

### ISSUE THREAD

**Issue by willisc7** [paketo-buildpacks/dotnet-core-build#79]
As a developer

I want to have the .NET buildpack detect and build when there are multiple module directories in the root of my git repo (e.g. `src/module1`, `src/module2`) that individually contain `.csproj` files

So that I can continue build my C# applications in a modular way that makes them more maintainable long term.

**Comment by ForestEckhardt** [comment]
@willisc7 Just to clarify, you would like to be able to more easily specify the root of your project to allow you to build multiple images from a single repository? So adding something like an environment variable that would let you do 
```shell
pack build foo -e SOME_ENVIRONMENT_VARIABLE=src/foo
pack build bar -e SOME_ENVIRONMENT_VARIABLE=src/bar
```
would be sufficient for your use case?

**Comment by floragj** [comment]
I'm guessing that @willisc7 is referring to [creating a multi-module assembly](https://flylib.com/books/en/3.228.1.77/1/) where different modules in the project can be compiled into DLLs before the whole application is packaged up. Is that the case?
